# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: HOANG VO KE
# Description of the Site
description: Hành trình vạn dặm khởi đầu bằng một bước chân. (The journey of a thousand miles begins with one step.)
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: "/assets/images/ricefield.jpg"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: "vo36@purdue.edu"
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Hoang Vo

# Name of the Author
author-name: Hoang Vo Ke
# URL for the Image of the Author
author-image: "/assets/images/HoangVo.jpeg"
# 60 Words About the Author
author-about: My name is Võ Kế Hoàng (you can call me Hoang). I am a PhD in mathematics at Purdue University. My hobbies including playing and listening to music, drawing, reading and writing poems (the Vietnamese ones of course), and playing with Linux. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
